#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    if command -v deb-systemd-helper >/dev/null 2>&1; then
        deb-systemd-helper enable infiltrator-software-auto-update.timer >/dev/null || true
        deb-systemd-helper enable infiltrator-software-maintenance.timer >/dev/null || true
    fi
    if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
        systemctl daemon-reload >/dev/null 2>&1 || true
        systemctl start infiltrator-software-auto-update.timer >/dev/null 2>&1 || true
        systemctl start infiltrator-software-maintenance.timer >/dev/null 2>&1 || true
    fi
fi

#DEBHELPER#

exit 0
